//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public int IdAdministrador { get; set; }
        public string NombresAdministrador { get; set; }
        public string ApellidosAdministrador { get; set; }
        public string UsuarioAdministrador { get; set; }
        public string PasswordAdministrador { get; set; }
    }
}
