//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservaEcologica
    {
        public int IdReservaEcologica { get; set; }
        public string nombreReservaEcologica { get; set; }
        public string ImagenReservaEcologica { get; set; }
        public string ProvinciaReservaEcologica { get; set; }
        public string DescripcionReservaEcologica { get; set; }
        public string SitioWebReservaEcologica { get; set; }
    
        public virtual Posicion Posicion { get; set; }
    }
}
